
export const ACADEMIC_XP_LEVELS = {
  LEVEL_1: 0,
  LEVEL_2: 100,
  LEVEL_3: 250,
  LEVEL_4: 500,
  LEVEL_5: 900,
};

export const WORK_XP_LEVELS = {
  LEVEL_1: 0,
  LEVEL_2: 150,
  LEVEL_3: 350,
  LEVEL_4: 700,
  LEVEL_5: 1200,
};
export const AcademicActionsXp = {
  STUDY_DAY: 10,
  FINISH_COURSE: 50,
  GOOD_PERFORMANCE: 20,
  USE_RESOURCE: 5,
};

export const WorkActionsXp = {
  WORK_DAY: 15,
  PROJECT_DONE: 40,
  STABLE_JOB: 25,
  ENTREPRENEURSHIP: 30,
};

export const PROVINCIAS_ESPAÑA = [
  { "label": "Álava", "value": "alava", "avgRoomRent": 450 },
  { "label": "Albacete", "value": "albacete", "avgRoomRent": 300 },
  { "label": "Alicante", "value": "alicante", "avgRoomRent": 400 },
  { "label": "Almería", "value": "almeria", "avgRoomRent": 320 },
  { "label": "Asturias", "value": "asturias", "avgRoomRent": 380 },
  { "label": "Ávila", "value": "avila", "avgRoomRent": 250 },
  { "label": "Badajoz", "value": "badajoz", "avgRoomRent": 240 },
  { "label": "Balears, Illes", "value": "illes_balears", "avgRoomRent": 500 },
  { "label": "Barcelona", "value": "barcelona", "avgRoomRent": 620 },
  { "label": "Bizkaia", "value": "bizkaia", "avgRoomRent": 520 },
  { "label": "Burgos", "value": "burgos", "avgRoomRent": 280 },
  { "label": "Cáceres", "value": "caceres", "avgRoomRent": 230 },
  { "label": "Cádiz", "value": "cadiz", "avgRoomRent": 310 },
  { "label": "Cantabria", "value": "cantabria", "avgRoomRent": 380 },
  { "label": "Castellón", "value": "castellon", "avgRoomRent": 290 },
  { "label": "Ceuta", "value": "ceuta", "avgRoomRent": 350 },
  { "label": "Ciudad Real", "value": "ciudad_real", "avgRoomRent": 190 },
  { "label": "Córdoba", "value": "cordoba", "avgRoomRent": 260 },
  { "label": "Cuenca", "value": "cuenca", "avgRoomRent": 280 },
  { "label": "Girona", "value": "girona", "avgRoomRent": 470 },
  { "label": "Granada", "value": "granada", "avgRoomRent": 300 },
  { "label": "Guadalajara", "value": "guadalajara", "avgRoomRent": 290 },
  { "label": "Gipuzkoa", "value": "gipuzkoa", "avgRoomRent": 550 },
  { "label": "Huelva", "value": "huelva", "avgRoomRent": 210 },
  { "label": "Huesca", "value": "huesca", "avgRoomRent": 300 },
  { "label": "Jaén", "value": "jaen", "avgRoomRent": 250 },
  { "label": "La Rioja", "value": "la_rioja", "avgRoomRent": 330 },
  { "label": "Las Palmas", "value": "las_palmas", "avgRoomRent": 360 },
  { "label": "León", "value": "leon", "avgRoomRent": 270 },
  { "label": "Lleida", "value": "lleida", "avgRoomRent": 340 },
  { "label": "Lugo", "value": "lugo", "avgRoomRent": 240 },
  { "label": "Madrid", "value": "madrid", "avgRoomRent": 600 },
  { "label": "Málaga", "value": "malaga", "avgRoomRent": 440 },
  { "label": "Murcia", "value": "murcia", "avgRoomRent": 320 },
  { "label": "Navarra", "value": "navarra", "avgRoomRent": 480 },
  { "label": "Ourense", "value": "ourense", "avgRoomRent": 240 },
  { "label": "Palencia", "value": "palencia", "avgRoomRent": 230 },
  { "label": "Pontevedra", "value": "pontevedra", "avgRoomRent": 290 },
  { "label": "Salamanca", "value": "salamanca", "avgRoomRent": 280 },
  { "label": "Santa Cruz de Tenerife", "value": "santa_cruz_de_tenerife", "avgRoomRent": 400 },
  { "label": "Segovia", "value": "segovia", "avgRoomRent": 260 },
  { "label": "Sevilla", "value": "sevilla", "avgRoomRent": 380 },
  { "label": "Soria", "value": "soria", "avgRoomRent": 250 },
  { "label": "Tarragona", "value": "tarragona", "avgRoomRent": 310 },
  { "label": "Teruel", "value": "teruel", "avgRoomRent": 280 },
  { "label": "Toledo", "value": "toledo", "avgRoomRent": 330 },
  { "label": "València", "value": "valencia", "avgRoomRent": 410 },
  { "label": "Valladolid", "value": "valladolid", "avgRoomRent": 290 },
  { "label": "Vizcaya", "value": "vizcaya", "avgRoomRent": 510 },
  { "label": "Zamora", "value": "zamora", "avgRoomRent": 240 },
  { "label": "Zaragoza", "value": "zaragoza", "avgRoomRent": 380 },
  { "label": "Melilla", "value": "melilla", "avgRoomRent": 330 }
]
